name: mobile1_flutter_coding_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Routing
  go_router: ^17.0.0

  # Sensors
  sensors_plus: ^7.0.0

  # Desktop Window Management
  window_manager: ^0.5.1

  # Network
  network_info_plus: ^7.0.0

  # Permissions
  permission_handler: ^12.0.1

  # Code Generation (Annotations)
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
